Repository januarythirtyfirst/AdventureTimeTranslate, pull requests merged in 2021-01, with the labels that each got.

#34 Sophiabranch
  README.md
Labels: bug

#38 Barbarabranch
  s5/007.srt
Labels: 30 lines

#59 translate 007.srt
  s5/007.srt
Labels: 30 lines

#74 Translate twenty eight lines
  s5/007.srt
Labels: 10 lines

#75 I translate 44 lines
  s5/007.srt
Labels: 10 lines
